clc;
clear all;
t=-1.5:.035:2;
x1=cos(4*t);
subplot(3,1,1);
plot(t,x1);
xlabel('t');
ylabel('x(t)');
title('Activity 1 (c)');
x2=2*sin(8*t);
subplot(3,1,2);
plot(t,x2);
xlabel('t');
ylabel('x(t)');
x=cos(4*t)+2*sin(8*t);
subplot(3,1,3);
plot(t,x);
xlabel('t');
ylabel('x(t)');
