clc;
clear all;
n1=-2:20;
x=exp(-n1);
n2=-2:10;
h=(-2).^n2;
[y,m]=convm(x,n1,h,n2);
subplot(3,1,1);
stem(n1,x);
xlabel('n');
ylabel('x[n]');
title('Activity 1 A');
subplot(3,1,2);
stem(n2,h);
xlabel('n');
ylabel('h[n]');
subplot(3,1,3);
stem(m,y);
xlabel('n');
ylabel('y[n]');